// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // A CLI (migrate, resolve, seed) usa a ligação direta — o pooler da Neon (PgBouncer,
    // modo transação) não suporta os locks de sessão que o Prisma Migrate precisa.
    // O runtime da app usa DATABASE_URL (pooled) via src/lib/prisma.ts, não este ficheiro.
    url: process.env["DIRECT_URL"],
  },
});
